export {default as Home} from './Home';
export {default as Match} from './Match';
// export {default as LeagueMain} from '../League/LeagueMain';
export {default as Team} from './Team';
export {default as QnA} from './QnA';
export {default as Gujang} from './Match_Gujang';
export {default as Reservation} from './Reservation';
export {default as JoinFinal} from './JoinFinal';
export {default as JoinForm } from './JoinForm';
export {default as LoginForm} from './LoginForm';
export {default as Payment} from './Payment';
export {default as TeamHome} from './TeamHome';
export {default as TeamMember} from './TeamMember';
export {default as MatchHistory} from './MatchHistory';
export {default as TeamBoard} from './TeamBoard';
export {default as TWrite} from './TWrite';
export {default as Mypage} from './Mypage';
export {default as MyMatchHistory} from './MyMatchHistory';
export {default as Account} from './Account';
export {default as PointHistory} from './PointHistory';
export {default as Write} from './Write';
export {default as CreateTeam} from './CreateTeam';
export {default as PwdCheck} from './PwdCheck';
export {default as PwdChange} from './PwdChange';
export {default as TCSuccess} from './TCSuccess';
export {default as ReservationHistory} from './ReservationHistory';
export {default as PointCharge} from './PointCharge';